// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ProjectOne.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260913152955_Intital")]
    partial class Intital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectOne.Domain.Classes.Rentalagreement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<Guid>("StorageId")
                        .HasColumnType("uuid")
                        .HasColumnName("storage_id");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_price");

                    b.HasKey("Id")
                        .HasName("pk_rental_agreement");

                    b.HasIndex("StorageId")
                        .HasDatabaseName("ix_rental_agreement_storage_id");

                    b.ToTable("RentalAgreement", (string)null);
                });

            modelBuilder.Entity("ProjectOne.Domain.Classes.StorageCell", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("Floor")
                        .HasColumnType("integer")
                        .HasColumnName("Floor");

                    b.Property<string>("NumberStorageCalls")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("number_storage_calls");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("Price");

                    b.Property<int>("Size")
                        .HasColumnType("integer")
                        .HasColumnName("Size");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<Guid>("WareHouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("ware_house_id");

                    b.HasKey("Id")
                        .HasName("pk_storage_cell");

                    b.HasIndex("WareHouseId")
                        .HasDatabaseName("ix_storage_cell_ware_house_id");

                    b.ToTable("StorageCell", (string)null);
                });

            modelBuilder.Entity("ProjectOne.Domain.Classes.WareHouse", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Address");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<int>("Floor")
                        .HasColumnType("integer")
                        .HasColumnName("Floor");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.HasKey("Id")
                        .HasName("pk_ware_house");

                    b.ToTable("WareHouse", (string)null);
                });

            modelBuilder.Entity("ProjectOne.Domain.Classes.Rentalagreement", b =>
                {
                    b.HasOne("ProjectOne.Domain.Classes.StorageCell", "StorageCell")
                        .WithMany()
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rental_agreement_storage_cell_storage_id");

                    b.Navigation("StorageCell");
                });

            modelBuilder.Entity("ProjectOne.Domain.Classes.StorageCell", b =>
                {
                    b.HasOne("ProjectOne.Domain.Classes.WareHouse", "WareHouse")
                        .WithMany("StorageCalls")
                        .HasForeignKey("WareHouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_storage_cell_ware_house_ware_house_id");

                    b.OwnsOne("ProjectOne.Domain.VO.SizeOfStorage", "SizeOfStorage", b1 =>
                        {
                            b1.Property<Guid>("StorageCellId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Depth")
                                .HasColumnType("integer")
                                .HasColumnName("Depth");

                            b1.Property<int>("Height")
                                .HasColumnType("integer")
                                .HasColumnName("Height");

                            b1.Property<int>("Width")
                                .HasColumnType("integer")
                                .HasColumnName("Width");

                            b1.HasKey("StorageCellId");

                            b1.ToTable("StorageCell");

                            b1.WithOwner()
                                .HasForeignKey("StorageCellId")
                                .HasConstraintName("fk_storage_cell_storage_cell_id");
                        });

                    b.Navigation("SizeOfStorage")
                        .IsRequired();

                    b.Navigation("WareHouse");
                });

            modelBuilder.Entity("ProjectOne.Domain.Classes.WareHouse", b =>
                {
                    b.Navigation("StorageCalls");
                });
#pragma warning restore 612, 618
        }
    }
}
